//tealium universal tag - utag.55 ut4.0.201808031344, Copyright 2018 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){(function(parent,name,context,definition){if(!context||!context[parent]||!Array.prototype.filter){return;}
context[parent]['plugins'][name]=definition();})('bactm','adobesensei',typeof window!=='undefined'?window:null,function(){var parent='bactm',ba=window[parent],win=window,doc=document||{},version='2.0.0',ddo=win.digitalData,LOG_LEVEL={OFF:10,FATAL:5,ERROR:4,WARN:3,INFO:2,DEBUG:1},secureTrackingServer='https://bankofamerica1.sc.omtrdc.net',firstLevelDirectory='b',secondLevelDirectory='ss',reportSuiteId='baam',hitSourceLookUpId='5',baseUrl=secureTrackingServer+'/'+firstLevelDirectory+'/'
+secondLevelDirectory+'/'+reportSuiteId+'/'+hitSourceLookUpId
+'/adobesensei'+version,bh=win.innerHeight,bw=win.innerWidth,ce='UTF-8',ndh=1,ns=doc.location.host,r=doc.referrer,v0=ba.QueryString(doc.location.href).get('cm_mmc'),bactmCookie=new ba.Cookies();if(!ddo)return;var _getEnvBasedOnHostname=function(hostname){var env='prod',hostname=hostname||window.location.hostname,hostnameParts=hostname.split('.').reverse(),devIndicators=['www-','secure-','-dev','-stg','dev-','qa-','review-','preview-','localhost'],indicatorsLen=devIndicators.length;if(hostnameParts.length>3&&hostnameParts[2]==='ecnp')env='dev';for(var i=0,partsLen=hostnameParts.length;i<partsLen;i++){if(env==='dev')break;var part=hostnameParts[i];for(var j=0;j<indicatorsLen;j++){var indicator=devIndicators[j];if(part.indexOf(indicator)>-1){env='dev';break;}}}
return env;}
var _getBaseUrl=function(){baseUrl=baseUrl.replace('baam','baam'+_getEnvBasedOnHostname());return baseUrl+'/s'+Date.now().toString();}
var _getDotsInDomain=function(domain){return domain.split('.').length-1;}
var _getTime=function(){var date=new Date();var year=date.getYear();year=year.length===3?year.substr(1,year.length):year;var month=(1+date.getMonth()).toString();month=month.length>1?month:'0'+month;var day=date.getDate().toString();day=day.length>1?day:'0'+day;var hours=date.getHours().toString();hours=hours.length>1?hours:'0'+hours;var minutes=date.getMinutes().toString();minutes=minutes.length>1?minutes:'0'+minutes;var seconds=date.getSeconds().toString();seconds=seconds.length>1?seconds:'0'+seconds;var D=date.getDay().toString();var offset=date.getTimezoneOffset()/60*-1;return(day+'/'+month+'/'+year+' '+hours+':'+
minutes+':'+seconds+' '+D+' '+offset);}
var _getQueryStringParamFromObject=function(obj){var qs='';var keys=Object.keys(obj);if(keys.length===0)return qs;for(var i=0;i<keys.length;i++){var key=keys[i];if(i===0){qs+=key+'='+encodeURI(obj[key]);}else{qs+='&'+encodeURI(key)+'='+encodeURI(obj[key]);}}
return qs;};var _getAdobeMID=function(){var c=new ba.Cookies();var bactmLts=c.get('bactm_lts')||null;var bactmCookie=JSON.parse(bactmLts);if(!bactmCookie)return'';return bactmCookie.adobeMID.d_mid;}
var _pageview=function(){var pageUrl=doc.location.href;var url='';var cdp=_getDotsInDomain(doc.location.origin);var g=pageUrl.substr(0,255);var _g='';var t=_getTime();if(pageUrl.length>255){_g=pageUrl.substr(256,pageUrl.length);}
var mid=_getAdobeMID();if(!mid){ba.log('Adobe Experience ID is not set');return;}
var qs={"bh":bh,"bw":bw,"cdp":cdp,"ce":ce,"g":g,"mid":mid,"ndh":ndh,"ns":ns,"pageName":ddo.page.pageInfo[0].pageID,"r":r,"t":t,};if(v0)qs.v0=v0;if(_g)qs['-g']=_g;var queryString=_getQueryStringParamFromObject(qs);var pixelTagSrc=_getBaseUrl()+'?AQB=1&'+queryString+'&AQE=1';var tag=new ba.PixelTag(pixelTagSrc);tag.appendToBody();};var _trackClick=function(e){var pageUrl=doc.location.href;var mid=_getAdobeMID();if(!mid){ba.log('Adobe Experience ID is not set');return;}
var cdp=_getDotsInDomain(doc.location.origin);var g=pageUrl.substr(0,255);var _g='';if(pageUrl.length>255){_g=pageUrl.substr(256,pageUrl.length);}
if(_g)qs['-g']=_g;var pe='0';var pev1=e.target.href;var pev2=e.target.id;var t=_getTime();var pageName=ddo.page.pageInfo[0].pageID;var qs={"cdp":cdp,"ce":ce,"g":g,"mid":mid,"ndh":ndh,"ns":ns,"pe":pe,"pev1":pev1,"pev2":pev2,"pageName":pageName,"t":t,};if(v0)qs.v0=v0;if(_g)qs['-g']=_g;var queryString=_getQueryStringParamFromObject(qs);var pixelTagSrc=_getBaseUrl()+'?AQB=1&'+queryString+'&AQE=1';var tag=new ba.PixelTag(pixelTagSrc);tag.appendToBody();};var _init=function(){ba._log('adobesensei plugin v'+version+' initializing.',LOG_LEVEL.INFO);_pageview();var anchorTags=doc.getElementsByTagName('a');for(var i=0;i<anchorTags.length;i++){var sp=ba.QueryString(anchorTags[i].href).get('cm_sp');if(!sp){continue;}
anchorTags[i].addEventListener('click',_trackClick);}};_init();return{};});}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("55","bofa.main");}catch(error){utag.DB(error);}
